server:
  port: 8080
  servlet:
    context-path: /auth
    session:
      cookie:
        name: SSO-SESSION

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fs_test?serverTimezone=GMT%2B8
    username: root
    password: 1234567890