server:
  port: 8080
  servlet:
    context-path:


spring:
  redis:
    port: 6379
    database: 0
    password: 123456
    host: localhost
#    sentinel:
#      master: local-master
#      nodes: 192.168.88.103:26380,192.168.88.103:26379
#      password: 123456
