server:
  port: 8081
  servlet:
    context-path: /client1

security:
  oauth2:
    client:
      client-id: client1
      client-secret: client1_secret
      access-token-uri: http://fcx.com/auth/oauth/token
      user-authorization-uri: http://fcx.com/auth/oauth/authorize
    resource:
      jwt:
        key-uri: http://fcx.com/auth/oauth/token_key