server:
  port: 8081
  servlet:
    context-path:

security:
  #以下必须配置，oauth2将自动去认证服务器取令牌相关的用户及角色
  oauth2:
    client:
      client-id: client1
      preEstablishedRedirectUri:
      client-secret: client1_secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/user
      token-info-uri: http://localhost:8080/oauth/check_token
